{{- if .Values.controller.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "foip-operator.fullname" . }}-controller
  labels:
    {{- include "foip-operator.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.controller.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "foip-operator.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: controller
{{- end }}
